services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: kogui-pokedex-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - DATABASE_URI=sqlite:///database.db
      - JWT_SECRET_KEY=your_jwt_secret_key
    volumes:
      - api_data:/app/instance
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: kogui-pokedex-web
    ports:
      - "${PORT:-3000}:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  api_data:
    driver: local

networks:
  app-network:
    driver: bridge