### Busca Pokémons
GET http://localhost:5000/api/pokemon
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MDc4NDI1MSwianRpIjoiMGI0YmM3YzMtYjM1MC00OTkxLTgxYmItYjA5MjBhMDM0NWE0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NjA3ODQyNTEsImNzcmYiOiJhMjg1NzJlNC1lYTM4LTQyMDUtOGMxYi1hMjIxN2E5NmU3N2EiLCJleHAiOjE3NjA3ODc4NTF9.3M_7nBio7gXzYEHQYyxKktDrd7D1uhjK6RETf-BHWQk


### Adiciona Pokémon como favorito
POST http://localhost:5000/api/pokemon/user/2/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MDc4Nzk1OSwianRpIjoiNGI0Yjg0NmYtMTU4NS00OGZkLTkyY2YtNTg5MTg1NzYzNTFiIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NjA3ODc5NTksImNzcmYiOiJiMmQ5YzNmOS04ZTBlLTQ4ZjMtOGRkYS1jZmE5ODNlM2FhMTgiLCJleHAiOjE3NjA3OTE1NTl9.qRkjN-fZ2RA_ytKCJl5QWALFDGaXFu7HSZCWQ7Ek2nE

### Adiciona Pokémon ao grupo de batalha
POST http://localhost:5000/api/pokemon/user/1/battle-group
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MDY0MDk3MCwianRpIjoiMGY4NjVjNWItYmVmNC00OWIxLTk0ZjQtY2MwYzY3NDFjNGZjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NjA2NDA5NzAsImNzcmYiOiJkNGExNDVjZi0yNjljLTQwMjUtODAyNC1lMGMzNDNjYjA1NDMiLCJleHAiOjE3NjA2NDQ1NzB9.DxIOXthqQzGGL6rTRUvZN5VayhWs0zTea3-TVMr3xVA