### Busca Pokémons
GET http://localhost:5000/api/pokemon
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MDY0MjAzMSwianRpIjoiMzY2NGM2ZmQtZjg0ZS00YzExLTg2N2ItOGJjNDZjNDM3YzI2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NjA2NDIwMzEsImNzcmYiOiIyMmEyYWQ5Ni1mY2U0LTRjODctODBkZS1kZTEwYmI5MDJmMzYiLCJleHAiOjE3NjA2NDU2MzF9.-wdF0TJgUIX4-M9Aa0LYGo9jWAAZypxC_gCqx6PWBis


### Adiciona Pokémon como favorito
POST http://localhost:5000/api/pokemon/user/2/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MDY0MDk3MCwianRpIjoiMGY4NjVjNWItYmVmNC00OWIxLTk0ZjQtY2MwYzY3NDFjNGZjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NjA2NDA5NzAsImNzcmYiOiJkNGExNDVjZi0yNjljLTQwMjUtODAyNC1lMGMzNDNjYjA1NDMiLCJleHAiOjE3NjA2NDQ1NzB9.DxIOXthqQzGGL6rTRUvZN5VayhWs0zTea3-TVMr3xVA

### Adiciona Pokémon ao grupo de batalha
POST http://localhost:5000/api/pokemon/user/1/battle-group
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MDY0MDk3MCwianRpIjoiMGY4NjVjNWItYmVmNC00OWIxLTk0ZjQtY2MwYzY3NDFjNGZjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NjA2NDA5NzAsImNzcmYiOiJkNGExNDVjZi0yNjljLTQwMjUtODAyNC1lMGMzNDNjYjA1NDMiLCJleHAiOjE3NjA2NDQ1NzB9.DxIOXthqQzGGL6rTRUvZN5VayhWs0zTea3-TVMr3xVA